name: '3-days-weather Bot'
 
on:
  push:
  schedule:
    - cron: '50 8,11,3 * * MON-FRI' # run at 4:50 evening, 7:50 morning and 11:50 afternoon in China
  workflow_dispatch:
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Weather'
        run: bash ./weather.sh
      - name: 'Get Date'
        run: echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          secure: true
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 3天天气预报 (${{env.REPORT_DATE}})
          body: 天气预报
          to: ${{ secrets.MAIL_RECEIPIENT }}
          from: wttr.in 天气预报
          content_type: text/html
          attachments: result.html
